export {default as Link} from '@b2storefront/b2s_core/dist/utils/Link'
export { default as SEO } from 'src/b2s_core/src/components/snippets/SEO'
export { Layout } from 'src/layouts/index.js'
export { slugify } from 'src/b2s_core/src/utils/helpers'
export { default as ReactMarkdown } from 'react-markdown'